[package]
name = "metaverse_avatar"
version = "0.3.3"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "Avatar handling for the open metaverse"
license = "AGPL-3.0-or-later"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/avatar"
edition = "2024"

exclude = ["tests/**/*"]

[dependencies]
metaverse_messages.workspace = true
benthic_default_asset_converter.workspace = true
benthic_protocol.workspace = true
metaverse_mesh.workspace = true 

byteorder.workspace = true 
strum.workspace = true 
strum_macros.workspace = true 
rgb.workspace = true 
uuid.workspace = true
glam.workspace = true
indexmap.workspace = true
serde_json.workspace = true 
serde.workspace = true 
actix.workspace = true 
thiserror.workspace = true 
log.workspace = true 
