[package]
name = "metaverse_session"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
metaverse_login = "0.0.2"
xmlrpc = "0.15.1"

