[package]
name = "metaverse_session"
version = "0.0.3"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "metaverse session handler"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
metaverse_messages = {path = "../messages/"}
metaverse_login = {path = "../login/"}
metaverse_instantiator = "0.0.4"
xmlrpc = "0.15.1"
actix-web = "3"
tokio = { version = "1.14.0", features = ["full"] }
tokio-test = "0.4.2"
env_logger = "0.9"
log = "0.4"
actix = "0.13.5"
hex = "0.4"
rand = "0.8"
futures = "0.3.30"
thiserror = "1.0.63"

actix-rt = "2.7"
[dependencies.uuid]
version = "1.10.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
