[package]
name = "login"
version = "0.1.0"
authors = ["wgahnagl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmlrpc = "0.15.0"
