[workspace]
members = [
	"crates/login", 
	"crates/session",
	"crates/messages",
  "crates/instantiator", 
  "crates/utils", "crates/chat", "crates/ui"]


[patch.crates-io]
# needed in order to accept data from osgrid servers
xmlrpc_benthic = {git = "https://github.com/benthic-mmo/xml-rpc-rs"}
