[package]
name = "metaverse_cache"
version = "0.2.0"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "inventory and cache handling for the open metaverse"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
metaverse_messages = {path="../messages/"}
metaverse_agent = {path="../agent/"}
anyhow = "1.0.104"
awc = "3.8.2"
dirs = "7.0.0"
log = "0.4.34"
serde-llsd-benthic = {path="../../../benthic-serde-llsd/"}
quick-xml = "0.42.0"
serde = "1.0.229"
thiserror = "2.0.20"
uuid = "1.26.1"

include_dir = "0.7.4"
serde_json = "1.0.151"
glam = "0.32.1"
rgb = "0.8.53"
sqlx = {version="0.9.0", features=["sqlite", "runtime-tokio"]}

[dev-dependencies]
tokio = {version = "1.53.1", features=["test-util"]}
httpmock = "0.8.3"
tempfile = "3.27.0"
