#this is the default config for an opensimulator server for testing
sim_url = "http://opensimulator.org/dist/OpenSim-LastAutoBuild.zip"
sim_archive = "sims/sim.zip"
sim_path = "sims/opensim"
sim_executable = "OpenSim.exe"
