[package]
name = "metaverse_objects"
version = "0.3.3"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "Metaverse objects, a crate for handling objects in Benthic"
license = "AGPL-3.0-or-later"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/objects"
edition = "2024"

[dependencies]
benthic_protocol.workspace = true 
metaverse_messages.workspace = true 
metaverse_avatar.workspace = true 
metaverse_cache.workspace = true 
benthic_default_asset_converter.workspace = true 
metaverse_mesh.workspace = true 

bytes.workspace = true
thiserror.workspace =true 
image.workspace = true 
jpeg2k.workspace = true 
uuid.workspace = true 
awc.workspace = true 
sqlx.workspace = true 
glam.workspace = true
log.workspace = true 
serde_json.workspace = true 
indexmap.workspace = true 
