[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
metaverse_session = {path = "../session/"}
metaverse_messages = {path = "../messages/"}
metaverse_login = {path = "../login/"}
bevy-tokio-tasks = {path = "../../../bevy-actix-tasks/"}
tokio = { version = "1", features = ["full"] }
actix-rt = "2.8.0"

