[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
metaverse_session = {path = "../session/"}
metaverse_messages = {path = "../messages/"}
metaverse_login = {path = "../login/"}
bevy-tokio-tasks = {path = "../../../bevy-actix-tasks/"}
tokio = { version = "1", features = ["full"] }
actix-rt = "2.10.0"
accesskit = "0.17.1"
tempfile = "3.17.1"
bevy_egui = "0.32.0"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5.14"
serde_json = "1.0"
[dependencies.uuid]
version = "1.13.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
