[package]
name = "benthic_default_asset_converter"
version = "0.3.2"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "A simple patching build script to download and convert benthic default assets to json represntations for use in the wider project."
license = "AGPL-3.0-or-later"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/default_asset_converter"
edition = "2024"
links = "benthic_default_asset_converter"

[build-dependencies]
benthic_protocol.workspace = true 

bvh_anim = "0.4.0"

bytemuck.workspace = true 
gltf.workspace = true 
uuid.workspace = true 
indexmap.workspace = true 
glam = {workspace=true, features=["serde"]}
serde.workspace = true 
serde_json.workspace = true 

[features]
animations = ["quaternius_adjustments"]
quaternius_adjustments = []


[dependencies]
benthic_protocol.workspace = true 

gltf.workspace = true 
gltf-json.workspace = true
once_cell.workspace = true 
anyhow.workspace = true 
glam.workspace = true 
serde.workspace = true 
serde_json.workspace = true 
strum.workspace = true 
strum_macros.workspace = true
uuid.workspace = true 
