[package]
name = "metaverse_messages"
version = "0.3.3"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "packet definitions for the open metaverse"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/messages"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
benthic_protocol.workspace = true 
serde-llsd-benthic.workspace = true 

mac_address = "1.1.8"
sys-info = "0.9.1"
bitflags = "2.13.2"
md-5 = "0.11.0"
hex = "0.4.3"
flate2 = "1.1.10"
chrono = "0.4.45"
base64 = "0.23.1"

bincode = { workspace=true, features = ["serde"] }
quick-xml.workspace = true 
log.workspace = true 
byteorder.workspace = true 
glam = {workspace=true, features=["serde"]}
serde.workspace = true 
serde_json.workspace = true 
thiserror.workspace = true 
rgb = {workspace=true, features=["serde"]}
bytemuck.workspace=true
strum.workspace = true 
strum_macros.workspace = true 
indexmap = {workspace=true, features = ["serde"]}
anyhow.workspace = true
once_cell.workspace = true 
[dependencies.uuid]
workspace=true
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]

