[package]
name = "benthic_protocol"
version = "0.3.3"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "Benthic protocol, an intermediate layer between metaverse protocols and client programs."
license = "AGPL-3.0-or-later"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/benthic_protocol"
edition = "2024"

[dependencies]
serde-llsd-benthic.workspace = true

arc = "0.0.1"

dirs.workspace = true 
anyhow.workspace = true
once_cell.workspace = true
sqlx = {workspace = true, features=["sqlite"]} 
glam = { workspace = true, features = ["serde"] }
indexmap = {workspace = true, features = ["serde"]}
rgb = {workspace = true, features=["serde"]}
serde.workspace = true  
serde_derive.workspace = true
serde_json.workspace = true 
strum.workspace = true 
strum_macros.workspace = true 
thiserror.workspace = true
uuid = {workspace = true , features=["serde"]} 
