[package]
name = "metaverse_core"
version = "0.2.0"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "core program for server and client IO"
license = "AGPL-3.0-or-later"
edition = "2024"

# Include the assets dir, which contains default assets and textures.
include = [
    "src/**",
    "Cargo.toml",
    "assets/**",
]

[dependencies]
metaverse_messages = {path="../messages"}
metaverse_environment = {path="../environment", optional = true}
metaverse_avatar = {path="../avatar", optional = true}
metaverse_cache = {path="../cache", optional = true}
metaverse_objects = {path = "../objects/"}
metaverse_mesh = {path="../../../metaverse_mesh"}
serde-llsd-benthic = {path="../../../benthic-serde-llsd"}
benthic_protocol = {path="../benthic_protocol/"}
default_asset_converter = {path="../default_asset_converter"}
tokio = { version = "1.53.1", features = ["full"] }
log = "0.4"
actix = "0.13.5"
thiserror = "2.0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam-channel = "0.5.17"
actix-rt = "2.13"
bincode = { version = "2.0.1", features = ["serde"] }
portpicker = "0.1.1"
glam = {version = "0.32.1", features = ["serde"]}
actix-http = "3.13.5"
awc = "3.8.2"
quick-xml = "0.42.0"
dirs = "7.0.0"
bytemuck = "1.25.2"
bytes = "1.12.1"
indexmap = "2.14.2"
jpeg2k = "0.10.1"
image = "0.25.10"
sqlx = {version="0.9.0", features=["runtime-tokio"]}
url = "2.5.8"
rgb = "0.8.53"
[dependencies.uuid]
version = "1.26.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
bevy = "0.19.0"
bevy_world_serialization = "0.19.0"
bevy_panorbit_camera = "0.35.0"
lazy_static = "1.5.0"

# allow for compiling a barebones viewer
[features]
default = ["environment", "avatar", "inventory"]

# allow for compiling the viewer without any environment rendering
environment = ["dep:metaverse_environment"]
# allow for compiling the viewer without any agent rendering 
avatar = ["dep:metaverse_avatar"]

inventory = ["dep:metaverse_cache"]


