[package]
name = "metaverse_core"
version = "0.3.3"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "core program for server and client IO"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/core"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
metaverse_objects.workspace = true 
metaverse_mesh.workspace = true 
benthic_protocol.workspace = true 
metaverse_messages.workspace = true
serde-llsd-benthic.workspace = true 
metaverse_environment = {workspace=true, optional = true }
metaverse_avatar = { workspace=true, optional = true }
metaverse_cache = { workspace=true, optional = true }
benthic_default_asset_converter = {workspace=true, features = ["animations"]}

tokio = { workspace=true, features = ["full"] }
log.workspace = true 
actix.workspace = true 
thiserror.workspace = true
serde.workspace = true 
serde_json.workspace = true
rgb.workspace = true 
sqlx.workspace = true
indexmap.workspace = true 
awc.workspace = true 
glam = {workspace=true, features = ["serde"]}
actix-http.workspace = true 
url.workspace = true 
bytes.workspace = true 
actix-rt.workspace = true 
crossbeam-channel.workspace = true 
bincode = {workspace=true, features = ["serde"] }
portpicker.workspace = true 
jpeg2k.workspace = true 
image.workspace = true 
[dependencies.uuid]
workspace=true
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
bevy.workspace = true 
bevy_world_serialization.workspace = true 
bevy_panorbit_camera.workspace = true 
lazy_static.workspace = true


# allow for compiling a barebones viewer
[features]
default = ["environment", "avatar", "inventory"]

# allow for compiling the viewer without any environment rendering
environment = ["dep:metaverse_environment"]
# allow for compiling the viewer without any agent rendering 
avatar = ["dep:metaverse_avatar"]

inventory = ["dep:metaverse_cache"]


