[package]
name = "metaverse_environment"
version = "0.3.2"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "metaverse environment data handler"
license = "AGPL-3.0-or-later"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/metaverse_client/tree/main/crates/environment"
edition = "2024"

[dependencies]
metaverse_messages.workspace = true 
benthic_protocol.workspace = true 
metaverse_mesh.workspace = true 

twox-hash = "2.1.4"
bitreader = "0.3.11"

bytemuck = {workspace=true, features = ["derive"] }
byteorder.workspace = true 
glam = {workspace = true, features=["serde"]}
gltf.workspace = true 
gltf-json.workspace = true 
log.workspace = true 
once_cell.workspace = true 
uuid.workspace = true 
image.workspace = true 
thiserror.workspace = true 
awc.workspace = true
